apiVersion: v1
kind: Service
metadata:
  name: mysql-wordpress
  namespace: atividade-k8s
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql-wordpress