apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: atividade-k8s
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80