apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: atividade-k8s
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      volumes:
        - name: wordpress
          hostPath:
            path: /var/www/html
            type: DirectoryOrCreate
      containers:
        - name: wordpress
          image: wordpress:php8.2-apache
          imagePullPolicy: IfNotPresent
          ports:
            - name: wordpress
              containerPort: 80
          env:
            - name: WORDPRESS_DB_NAME
              value: wordpress_db
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress_password
            - name: WORDPRESS_DB_USER
              value: wordpress_user
            - name: WORDPRESS_DB_HOST
              value: mysql-wordpress:3306
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
              ephemeral-storage: 1Gi
            limits:
              memory: 512Mi
              cpu: 500m
              ephemeral-storage: 5Gi
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
            httpGet: null
            tcpSocket:
              port: 80
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
            httpGet: null
            tcpSocket:
              port: 80
